2023-07-11 14:00:15,047 - ERROR: Error Controladora Device 10.117.115.111
2023-07-11 14:00:15,047 - ERROR: Error Controladora Device 10.117.115.111
2023-07-11 14:00:15,048 - ERROR: Traceback (most recent call last):
  File "/home/donkami/Sona/SistemaDCS/DCS-Candelaria/Services/Mesh/controladora.py", line 31, in get_data_controladora
    output = net_connect.send_command("sh wireless client mac-address " + data_pala.split()[0] + " detail")
IndexError: list index out of range

2023-07-11 14:00:15,048 - ERROR: Traceback (most recent call last):
  File "/home/donkami/Sona/SistemaDCS/DCS-Candelaria/Services/Mesh/controladora.py", line 31, in get_data_controladora
    output = net_connect.send_command("sh wireless client mac-address " + data_pala.split()[0] + " detail")
IndexError: list index out of range

2023-07-11 14:00:52,320 - ERROR: Error Controladora Device 10.117.115.180
2023-07-11 14:00:52,320 - ERROR: Error Controladora Device 10.117.115.180
2023-07-11 14:00:52,320 - ERROR: Traceback (most recent call last):
  File "/home/donkami/Sona/SistemaDCS/DCS-Candelaria/Services/Mesh/controladora.py", line 31, in get_data_controladora
    output = net_connect.send_command("sh wireless client mac-address " + data_pala.split()[0] + " detail")
IndexError: list index out of range

2023-07-11 14:00:52,320 - ERROR: Traceback (most recent call last):
  File "/home/donkami/Sona/SistemaDCS/DCS-Candelaria/Services/Mesh/controladora.py", line 31, in get_data_controladora
    output = net_connect.send_command("sh wireless client mac-address " + data_pala.split()[0] + " detail")
IndexError: list index out of range

2023-07-11 14:01:31,008 - ERROR: Error Controladora Device 10.117.115.121
2023-07-11 14:01:31,008 - ERROR: Error Controladora Device 10.117.115.121
2023-07-11 14:01:31,008 - ERROR: Traceback (most recent call last):
  File "/home/donkami/Sona/SistemaDCS/DCS-Candelaria/Services/Mesh/controladora.py", line 31, in get_data_controladora
    output = net_connect.send_command("sh wireless client mac-address " + data_pala.split()[0] + " detail")
IndexError: list index out of range

2023-07-11 14:01:31,008 - ERROR: Traceback (most recent call last):
  File "/home/donkami/Sona/SistemaDCS/DCS-Candelaria/Services/Mesh/controladora.py", line 31, in get_data_controladora
    output = net_connect.send_command("sh wireless client mac-address " + data_pala.split()[0] + " detail")
IndexError: list index out of range

2023-07-11 14:02:33,934 - ERROR: Error Controladora Device 10.117.115.183
2023-07-11 14:02:33,934 - ERROR: Error Controladora Device 10.117.115.183
2023-07-11 14:02:33,934 - ERROR: Traceback (most recent call last):
  File "/home/donkami/Sona/SistemaDCS/DCS-Candelaria/Services/Mesh/controladora.py", line 48, in get_data_controladora
    connected_for = connected_for_match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

2023-07-11 14:02:33,934 - ERROR: Traceback (most recent call last):
  File "/home/donkami/Sona/SistemaDCS/DCS-Candelaria/Services/Mesh/controladora.py", line 48, in get_data_controladora
    connected_for = connected_for_match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

2023-07-11 14:03:47,702 - ERROR: Error Controladora Device 10.117.115.111
2023-07-11 14:03:47,702 - ERROR: Error Controladora Device 10.117.115.111
2023-07-11 14:03:47,703 - ERROR: Traceback (most recent call last):
  File "/home/donkami/Sona/SistemaDCS/DCS-Candelaria/Services/Mesh/controladora.py", line 31, in get_data_controladora
    output = net_connect.send_command("sh wireless client mac-address " + data_pala.split()[0] + " detail")
IndexError: list index out of range

2023-07-11 14:03:47,703 - ERROR: Traceback (most recent call last):
  File "/home/donkami/Sona/SistemaDCS/DCS-Candelaria/Services/Mesh/controladora.py", line 31, in get_data_controladora
    output = net_connect.send_command("sh wireless client mac-address " + data_pala.split()[0] + " detail")
IndexError: list index out of range

2023-07-11 14:04:25,821 - ERROR: Error Controladora Device 10.117.115.180
2023-07-11 14:04:25,821 - ERROR: Error Controladora Device 10.117.115.180
2023-07-11 14:04:25,821 - ERROR: Traceback (most recent call last):
  File "/home/donkami/Sona/SistemaDCS/DCS-Candelaria/Services/Mesh/controladora.py", line 31, in get_data_controladora
    output = net_connect.send_command("sh wireless client mac-address " + data_pala.split()[0] + " detail")
IndexError: list index out of range

2023-07-11 14:04:25,821 - ERROR: Traceback (most recent call last):
  File "/home/donkami/Sona/SistemaDCS/DCS-Candelaria/Services/Mesh/controladora.py", line 31, in get_data_controladora
    output = net_connect.send_command("sh wireless client mac-address " + data_pala.split()[0] + " detail")
IndexError: list index out of range

